version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
          command: npm run cy:run:ci
          post-steps:
            - store_test_results:
                path: cypress/reports
            - store_artifacts:
                path: cypress/reports