version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/install:
          install-command: 'npm install cypress-mochawesome-reporter junit-report-merger mocha-junit-reporter cypress-multi-reporters mocha'
      - cypress/run:
          requires:
            - cypress/install
          command: npm run cy:ci
          post-steps:
            - store_test_results:
                path: cypress/reports
            - store_artifacts:
                path: cypress/reports